/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_comp_grafica;

import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import proyecto1_comp_grafica.MisPaneles.PanelCirculo;
import proyecto1_comp_grafica.MisPaneles.PanelCuadrado;
import proyecto1_comp_grafica.MisPaneles.PanelElipse;
import proyecto1_comp_grafica.MisPaneles.PanelLinea;
import proyecto1_comp_grafica.MisPaneles.PanelPoligono;
import proyecto1_comp_grafica.MisPaneles.PanelTriangulo;

/**
 *
 * @author jorgeandrade
 */
public class Pantalla_Principal extends javax.swing.JFrame {

    GridBagLayout layout = new GridBagLayout ();
    PanelLinea linea1;
    PanelCuadrado cuadrado1;
    PanelPoligono poligono1;
    PanelTriangulo triangulo1;
    PanelCirculo circulo1;
    PanelElipse elipse1;
    
    public Pantalla_Principal() {
        initComponents();
        
        linea1 = new PanelLinea();
        cuadrado1 = new PanelCuadrado();
        poligono1 = new PanelPoligono();
        triangulo1 = new PanelTriangulo();
        circulo1 = new PanelCirculo();
        elipse1 = new PanelElipse();
        PanelDinamico.setLayout(layout);
        
        
      GridBagConstraints c = new GridBagConstraints();
        
        c.gridx=0;
        c.gridy=0;
        
        PanelDinamico.add(linea1,c);
        
        c.gridx=0;
        c.gridy=0;
        
        PanelDinamico.add(cuadrado1,c);
        
        c.gridx=0;
        c.gridy=0;
        
        PanelDinamico.add(poligono1,c);
        
        c.gridx=0;
        c.gridy=0;
        
        PanelDinamico.add(triangulo1,c);
        
        c.gridx=0;
        c.gridy=0;
        
        PanelDinamico.add(circulo1,c);
        
        c.gridx=0;
        c.gridy=0;
        
        PanelDinamico.add(elipse1,c);
        
        linea1.setVisible(false);
        cuadrado1.setVisible(false);
        poligono1.setVisible(false);
        triangulo1.setVisible(false);
        circulo1.setVisible(false);
        elipse1.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        PanelBotones = new javax.swing.JPanel();
        poligono = new javax.swing.JButton();
        cuadrado = new javax.swing.JButton();
        linea = new javax.swing.JButton();
        triangulo = new javax.swing.JButton();
        Elipse = new javax.swing.JButton();
        circulo = new javax.swing.JButton();
        PanelDinamico = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        MenuSalir = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        PanelBotones.setBackground(new java.awt.Color(0, 153, 153));
        PanelBotones.setPreferredSize(new java.awt.Dimension(150, 631));

        poligono.setText("Poligono");
        poligono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poligonoActionPerformed(evt);
            }
        });

        cuadrado.setText("Cuadrado");
        cuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuadradoActionPerformed(evt);
            }
        });

        linea.setText("Linea");
        linea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lineaActionPerformed(evt);
            }
        });

        triangulo.setText("Triangulo");
        triangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trianguloActionPerformed(evt);
            }
        });

        Elipse.setText("Elipse");
        Elipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ElipseActionPerformed(evt);
            }
        });

        circulo.setText("Circulo");
        circulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                circuloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBotonesLayout = new javax.swing.GroupLayout(PanelBotones);
        PanelBotones.setLayout(PanelBotonesLayout);
        PanelBotonesLayout.setHorizontalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Elipse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(circulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(triangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(poligono, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                    .addComponent(linea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelBotonesLayout.setVerticalGroup(
            PanelBotonesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBotonesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(linea, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(poligono, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(triangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(circulo, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Elipse, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(PanelBotones, java.awt.BorderLayout.LINE_START);

        PanelDinamico.setBackground(new java.awt.Color(153, 0, 51));

        javax.swing.GroupLayout PanelDinamicoLayout = new javax.swing.GroupLayout(PanelDinamico);
        PanelDinamico.setLayout(PanelDinamicoLayout);
        PanelDinamicoLayout.setHorizontalGroup(
            PanelDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 761, Short.MAX_VALUE)
        );
        PanelDinamicoLayout.setVerticalGroup(
            PanelDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );

        getContentPane().add(PanelDinamico, java.awt.BorderLayout.CENTER);

        jMenu2.setText("Archivo");

        jMenuItem1.setText("Guardar");
        jMenu2.add(jMenuItem1);

        MenuSalir.setText("Salir");
        MenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuSalirActionPerformed(evt);
            }
        });
        jMenu2.add(MenuSalir);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Edit");
        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void MenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MenuSalirActionPerformed

    private void lineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lineaActionPerformed
        linea1.setVisible(true);
        cuadrado1.setVisible(false);
        poligono1.setVisible(false);
    }//GEN-LAST:event_lineaActionPerformed

    private void cuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuadradoActionPerformed
        cuadrado1.setVisible(true);
        linea1.setVisible(false);
        poligono1.setVisible(false);
    }//GEN-LAST:event_cuadradoActionPerformed

    private void poligonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poligonoActionPerformed
         poligono1.setVisible(true);
        linea1.setVisible(false);
        cuadrado1.setVisible(false);
    }//GEN-LAST:event_poligonoActionPerformed

    private void ElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ElipseActionPerformed
        poligono1.setVisible(false);
        linea1.setVisible(false);
        cuadrado1.setVisible(false);
        triangulo1.setVisible(false);
        circulo1.setVisible(false);
        elipse1.setVisible(true);
    }//GEN-LAST:event_ElipseActionPerformed

    private void trianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trianguloActionPerformed
       poligono1.setVisible(false);
        linea1.setVisible(false);
        cuadrado1.setVisible(false);
        triangulo1.setVisible(true);
        circulo1.setVisible(false);
        elipse1.setVisible(false);
    }//GEN-LAST:event_trianguloActionPerformed

    private void circuloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_circuloActionPerformed
        poligono1.setVisible(false);
        linea1.setVisible(false);
        cuadrado1.setVisible(false);
        triangulo1.setVisible(false);
        circulo1.setVisible(true);
        elipse1.setVisible(false);
    }//GEN-LAST:event_circuloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pantalla_Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Elipse;
    private javax.swing.JMenuItem MenuSalir;
    private javax.swing.JPanel PanelBotones;
    private javax.swing.JPanel PanelDinamico;
    private javax.swing.JButton circulo;
    private javax.swing.JButton cuadrado;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JButton linea;
    private javax.swing.JButton poligono;
    private javax.swing.JButton triangulo;
    // End of variables declaration//GEN-END:variables
}
