/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_comp_grafica.MisPaneles;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.geom.Rectangle2D;
import java.util.Random;
import proyecto1_comp_grafica.Metodos;

/**
 *
 * @author jorgeandrade
 */
public class PanelCuadrado extends javax.swing.JPanel {

    /**
     * Creates new form PanelCuadrado
     */
    public PanelCuadrado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        yinicial = new javax.swing.JTextField();
        xinicial = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lado = new javax.swing.JTextField();
        DibujarCuadrado = new javax.swing.JButton();
        BorrarCuadrado = new javax.swing.JButton();
        TrasladarCuadrado = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        trasy = new javax.swing.JTextField();
        trasx = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EscalarCuadrado = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        esc = new javax.swing.JTextField();
        RellenarElipse = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        PanelDibujoCuadrado = new javax.swing.JPanel();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setText("Elija una opción (Dibujar/Transformar):");

        jLabel2.setText("Punto inicial:");

        jLabel3.setText("X:");

        jLabel4.setText("Y:");

        yinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yinicialActionPerformed(evt);
            }
        });

        xinicial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xinicialActionPerformed(evt);
            }
        });

        jLabel5.setText("Tamaño del lado:");

        lado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ladoActionPerformed(evt);
            }
        });

        DibujarCuadrado.setBackground(new java.awt.Color(153, 204, 255));
        DibujarCuadrado.setText("Dibujar");
        DibujarCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DibujarCuadradoActionPerformed(evt);
            }
        });

        BorrarCuadrado.setBackground(new java.awt.Color(255, 102, 102));
        BorrarCuadrado.setText("Borrar");
        BorrarCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarCuadradoActionPerformed(evt);
            }
        });

        TrasladarCuadrado.setText("Trasladar");
        TrasladarCuadrado.setEnabled(false);
        TrasladarCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrasladarCuadradoActionPerformed(evt);
            }
        });

        jLabel8.setText("Trasladar:");

        trasy.setEnabled(false);

        trasx.setEnabled(false);

        jLabel9.setText("X");

        jLabel10.setText("Y");

        EscalarCuadrado.setText("Escalar");
        EscalarCuadrado.setEnabled(false);
        EscalarCuadrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscalarCuadradoActionPerformed(evt);
            }
        });

        jLabel11.setText("Escalar:");

        esc.setEnabled(false);

        RellenarElipse.setText("Rellenar");
        RellenarElipse.setEnabled(false);
        RellenarElipse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RellenarElipseActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Rojo", "Azul", "Verde", "Amarillo" }));
        jComboBox1.setEnabled(false);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dibujar", "Transformar" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        PanelDibujoCuadrado.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelDibujoCuadradoLayout = new javax.swing.GroupLayout(PanelDibujoCuadrado);
        PanelDibujoCuadrado.setLayout(PanelDibujoCuadradoLayout);
        PanelDibujoCuadradoLayout.setHorizontalGroup(
            PanelDibujoCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelDibujoCuadradoLayout.setVerticalGroup(
            PanelDibujoCuadradoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 508, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3))
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(xinicial, javax.swing.GroupLayout.DEFAULT_SIZE, 48, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lado))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DibujarCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BorrarCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RellenarElipse, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(esc, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(EscalarCuadrado))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trasx, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trasy, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TrasladarCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(85, 85, 85))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelDibujoCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(yinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(xinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(lado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(DibujarCuadrado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BorrarCuadrado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TrasladarCuadrado)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(trasx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(trasy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(2, 2, 2)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(esc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EscalarCuadrado)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RellenarElipse)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDibujoCuadrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void yinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yinicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yinicialActionPerformed

    private void xinicialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xinicialActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_xinicialActionPerformed

    private void BorrarCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarCuadradoActionPerformed
        xinicial.setText(null);
        lado.setText(null);
        yinicial.setText(null);
       
        PanelDibujoCuadrado.removeAll();
        PanelDibujoCuadrado.repaint();
    }//GEN-LAST:event_BorrarCuadradoActionPerformed

    private void DibujarCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DibujarCuadradoActionPerformed
        Graphics t = PanelDibujoCuadrado.getGraphics();
    
        //obtener valores por teclado del usuario
        int x1,x2,y1,y2,incremento=1;
        int la=0;
        x1=Integer.parseInt(xinicial.getText());
        y1=Integer.parseInt(yinicial.getText());
        la=Integer.parseInt(lado.getText());
        
      
        Metodos obj =new Metodos();
        
   x2=x1+la;
   y2=y1;
   
   while(incremento != 5){
   
        obj.DDA(t,x1, y1, x2, y2);

        if (incremento==1){ 
            x1=Math.round(x2);
            y1=Math.round(y2);
           x2=Math.round(x2);
           y2=Math.round(y2)+la;
        }
        
        else if (incremento==2){
            x1=Math.round(x2);
            y1=Math.round(y2);
           x2=Math.round(x2)-la;
           y2=Math.round(y2);
        }
        
        else if (incremento==3)
        {
            x1=Math.round(x2);
        y1=Math.round(y2);
            x2=Math.round(x2);
           y2=Math.round(y2)-la;
        }
        
        incremento=incremento+1;
        
   }    
     
       
        
        
        
        
    }//GEN-LAST:event_DibujarCuadradoActionPerformed

    private void ladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ladoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ladoActionPerformed

    private void TrasladarCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrasladarCuadradoActionPerformed

       // PanelDibujoCuadrado.removeAll();
       // PanelDibujoCuadrado.repaint();

        int tx,ty;

        tx=Integer.parseInt(trasx.getText());
        ty=Integer.parseInt(trasy.getText());

        
        Graphics t = PanelDibujoCuadrado.getGraphics();
   
        //obtener valores por teclado del usuario
        int x1,x2,y1,y2,incremento=1;
        int la=0;
        x1=Integer.parseInt(xinicial.getText());
        y1=Integer.parseInt(yinicial.getText());
        la=Integer.parseInt(lado.getText());
        
   
        x1=x1+tx;
        y1=y1+ty;
        
        xinicial.setText(Integer.toString(x1));
        yinicial.setText(Integer.toString(y1));
        
        Metodos obj =new Metodos();
        
   x2=x1+la;
   y2=y1;
 
   while(incremento != 5){
       
      
        obj.DDA(t, x1, y1, x2, y2);

      
        if (incremento==1){ 
            x1=Math.round(x2);
            y1=Math.round(y2);
           x2=Math.round(x2);
           y2=Math.round(y2)+la;
        }
        
        else if (incremento==2){
            x1=Math.round(x2);
            y1=Math.round(y2);
           x2=Math.round(x2)-la;
           y2=Math.round(y2);
        }
        
        else if (incremento==3)
        {
            x1=Math.round(x2);
        y1=Math.round(y2)-1;
            x2=Math.round(x2);
           y2=Math.round(y2)-la;
        }
        
        incremento=incremento+1;
        
   }    
      

        
    }//GEN-LAST:event_TrasladarCuadradoActionPerformed

    private void EscalarCuadradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscalarCuadradoActionPerformed
       Graphics t = PanelDibujoCuadrado.getGraphics();

        //obtener valores por teclado del usuario
        int x1,x2,y1,y2,incremento=1, escalar,laescalar=0;
        int la=0;
        x1=Integer.parseInt(xinicial.getText());
        y1=Integer.parseInt(yinicial.getText());
        la=Integer.parseInt(lado.getText());
        escalar=Integer.parseInt(esc.getText());
        
        
     
        Metodos obj =new Metodos();
        
        
        if (escalar > 0){
            laescalar=la*escalar;
        }
        else if (escalar < 0){
            laescalar=la/-escalar;
        }
        
   x2=x1+laescalar;
   y2=y1;
  
   lado.setText(Integer.toString(laescalar));
   
        while(incremento != 5){
       
      
        obj.DDA(t, x1, y1, x2, y2);

      
        if (incremento==1){ 
            x1=Math.round(x2);
            y1=Math.round(y2);
           x2=Math.round(x2);
           y2=Math.round(y2)+(laescalar);
        }
        
        else if (incremento==2){
            x1=Math.round(x2);
            y1=Math.round(y2);
           x2=Math.round(x2)-(laescalar);
           y2=Math.round(y2);
        }
        
        else if (incremento==3)
        {
            x1=Math.round(x2);
        y1=Math.round(y2)-1;
            x2=Math.round(x2);
           y2=Math.round(y2)-(laescalar);
        }
        
        incremento=incremento+1;
        
   }    
        
     
       
        

    }//GEN-LAST:event_EscalarCuadradoActionPerformed

    private void RellenarElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RellenarElipseActionPerformed
        
         Graphics t = PanelDibujoCuadrado.getGraphics();
         
         //obtener valores por teclado del usuario
        int x1,x2,y1,y2;
        int la=0;
        x1=Integer.parseInt(xinicial.getText());
        y1=Integer.parseInt(yinicial.getText());
        la=Integer.parseInt(lado.getText());
        
        
         x2=x1+la;
         y2=y1;
        
         
         
        if (jComboBox1.getSelectedItem()== "Rojo"){
            t.setColor(Color.red);
         t.fillRect(x1, y1, la, la);
        }
        else if (jComboBox1.getSelectedItem() == "Azul")
        {
            t.setColor(Color.blue);
         t.fillRect(x1, y1, la, la);
        }
        else if (jComboBox1.getSelectedItem() == "Verde")
        {
            t.setColor(Color.green);
         t.fillRect(x1, y1, la, la);
        }
        else if (jComboBox1.getSelectedItem() == "Amarillo")
        {
            t.setColor(Color.yellow);
         t.fillRect(x1, y1, la, la);
        }
             
       
        // t.fillPolygon(obj.puntosenx(), obj.puntoseny(), 100);
        
        
    }//GEN-LAST:event_RellenarElipseActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
         if (jComboBox2.getSelectedItem()== "Dibujar"){
            xinicial.setEnabled(true);
            yinicial.setEnabled(true);
            lado.setEnabled(true);
             DibujarCuadrado.setEnabled(true);
            esc.setEnabled(false);
            trasx.setEnabled(false);
            trasy.setEnabled(false);
            EscalarCuadrado.setEnabled(false);
            TrasladarCuadrado.setEnabled(false);
           
            jComboBox1.setEnabled(false);
            RellenarElipse.setEnabled(false);
            
        }
        else if (jComboBox2.getSelectedItem() == "Transformar")
        {
            xinicial.setEnabled(false);
            yinicial.setEnabled(false);
            lado.setEnabled(false);
             DibujarCuadrado.setEnabled(false);
            esc.setEnabled(true);
            trasx.setEnabled(true);
            trasy.setEnabled(true);
            EscalarCuadrado.setEnabled(true);
            TrasladarCuadrado.setEnabled(true);
           
            jComboBox1.setEnabled(true);
            RellenarElipse.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarCuadrado;
    private javax.swing.JButton DibujarCuadrado;
    private javax.swing.JButton EscalarCuadrado;
    private javax.swing.JPanel PanelDibujoCuadrado;
    private javax.swing.JButton RellenarElipse;
    private javax.swing.JButton TrasladarCuadrado;
    private javax.swing.JTextField esc;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField lado;
    private javax.swing.JTextField trasx;
    private javax.swing.JTextField trasy;
    private javax.swing.JTextField xinicial;
    private javax.swing.JTextField yinicial;
    // End of variables declaration//GEN-END:variables
}
