/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_comp_grafica.MisPaneles;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;
import javax.swing.JComboBox;
import proyecto1_comp_grafica.Metodos;

/**
 *
 * @author jorgeandrade
 */
public class PanelLinea extends javax.swing.JPanel {

    
    
    @Override
    public void paint(Graphics g) {
        super.paint(g); 
    }

    
    public PanelLinea() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        xinicial = new javax.swing.JTextField();
        xfinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yfinal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        yinicial = new javax.swing.JTextField();
        PanelDibujoLinea = new javax.swing.JPanel();
        DibujarLinea = new javax.swing.JButton();
        BotonBorrarLinea = new javax.swing.JButton();
        TrasladarLinea = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        trasy = new javax.swing.JTextField();
        trasx = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EscalarLinea = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        esc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        rotar = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Elija una opcion (Dibujar/Transformar):");

        jLabel2.setText("Punto 1:");

        jLabel3.setText("Punto 2:");

        jLabel4.setText("X");

        jLabel5.setText("X");

        yfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yfinalActionPerformed(evt);
            }
        });

        jLabel6.setText("Y");

        jLabel7.setText("Y");

        PanelDibujoLinea.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelDibujoLineaLayout = new javax.swing.GroupLayout(PanelDibujoLinea);
        PanelDibujoLinea.setLayout(PanelDibujoLineaLayout);
        PanelDibujoLineaLayout.setHorizontalGroup(
            PanelDibujoLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelDibujoLineaLayout.setVerticalGroup(
            PanelDibujoLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 509, Short.MAX_VALUE)
        );

        DibujarLinea.setBackground(new java.awt.Color(153, 204, 255));
        DibujarLinea.setText("Dibujar");
        DibujarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DibujarLineaActionPerformed(evt);
            }
        });

        BotonBorrarLinea.setBackground(new java.awt.Color(255, 102, 102));
        BotonBorrarLinea.setText("Borrar");
        BotonBorrarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarLineaActionPerformed(evt);
            }
        });

        TrasladarLinea.setText("Trasladar");
        TrasladarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrasladarLineaActionPerformed(evt);
            }
        });

        jLabel8.setText("Trasladar:");

        trasy.setEnabled(false);

        trasx.setEnabled(false);

        jLabel9.setText("X");

        jLabel10.setText("Y");

        EscalarLinea.setText("Escalar");
        EscalarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscalarLineaActionPerformed(evt);
            }
        });

        jLabel11.setText("Escalar:");

        esc.setEnabled(false);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dibujar", "Transformar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel13.setText("Rotar:");

        rotar.setEnabled(false);
        rotar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rotarActionPerformed(evt);
            }
        });

        jButton1.setText("Rotar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(DibujarLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BotonBorrarLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel13))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(esc, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                    .addComponent(rotar))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(EscalarLinea, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trasx, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(trasy, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TrasladarLinea)))
                        .addGap(0, 165, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PanelDibujoLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel12)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel12)
                .addGap(501, 501, 501))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(rotar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(esc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EscalarLinea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(trasx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(trasy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(TrasladarLinea))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BotonBorrarLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel2)
                                        .addComponent(xinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(yinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(xfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(yfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addComponent(DibujarLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(PanelDibujoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DibujarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DibujarLineaActionPerformed
        Graphics t = PanelDibujoLinea.getGraphics();
        
       Metodos obj = new Metodos();

        //obtener valores por teclado del usuario
        int x1,x2,y1,y2;
        x1=Integer.parseInt(xinicial.getText());
        y1=Integer.parseInt(yinicial.getText());
        x2=Integer.parseInt(xfinal.getText());
        y2=Integer.parseInt(yfinal.getText());
        
        
        
        
        obj.DDA(t,x1, y1, x2, y2);
        
      
        
        
    }//GEN-LAST:event_DibujarLineaActionPerformed

    private void yfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yfinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yfinalActionPerformed

    private void BotonBorrarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarLineaActionPerformed
        xinicial.setText(null);
        xfinal.setText(null);
        yinicial.setText(null);
        yfinal.setText(null);
        PanelDibujoLinea.removeAll();
        PanelDibujoLinea.repaint();
    }//GEN-LAST:event_BotonBorrarLineaActionPerformed

    private void TrasladarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrasladarLineaActionPerformed
        
        Graphics t = PanelDibujoLinea.getGraphics();
       
        
       // PanelDibujoLinea.removeAll();
       // PanelDibujoLinea.repaint();
        
        int tx,ty;
        
        tx=Integer.parseInt(trasx.getText());
        ty=Integer.parseInt(trasy.getText());
        
        int x1,x2,y1,y2;
        x1=Integer.parseInt(xinicial.getText());
        y1=Integer.parseInt(yinicial.getText());
        x2=Integer.parseInt(xfinal.getText());
        y2=Integer.parseInt(yfinal.getText());
        
        x1=x1+tx;
        y1=y1+ty;
        x2=x2+tx;
        y2=y2+ty;
     
        Metodos obj =new Metodos();
        
        obj.DDA(t, x1, y1, x2, y2);
   
    }//GEN-LAST:event_TrasladarLineaActionPerformed

    private void EscalarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscalarLineaActionPerformed
        Graphics t = PanelDibujoLinea.getGraphics();

        //obtener valores por teclado del usuario
        int x1,x2,y1,y2,escalar,deltax,deltay;
        x1=Integer.parseInt(xinicial.getText());
        y1=Integer.parseInt(yinicial.getText());
        x2=Integer.parseInt(xfinal.getText());
        y2=Integer.parseInt(yfinal.getText());
        
        escalar=Integer.parseInt(esc.getText());
    
        Metodos obj =new Metodos();
        
        deltax=x2-x1;
        deltay=y2-y1;
        
        
        
        if (escalar >0){
                    if(Math.abs(deltax)>Math.abs(deltay)){
                   x2=x2+((escalar-1)*deltax);
               }
               else if (Math.abs(deltay)>Math.abs(deltax)){
                   y2=y2+((escalar-1)*deltay);
               }
               else if (deltay==deltax){
                   x2=x2+((escalar-1)*deltax);
                   y2=y2+((escalar-1)*deltay);
               }
                    xfinal.setText(Integer.toString(x2));
                    yfinal.setText(Integer.toString(y2));
        }
        else if (escalar <0)
        {
                    if(Math.abs(deltax)>Math.abs(deltay)){
                   x2=x1+(deltax/-escalar);
               }
               else if (Math.abs(deltay)>Math.abs(deltax)){
                   y2=y1+(deltay/-escalar);
               }
               else if (deltay==deltax){
                   x2=x1+(deltax/-escalar);
                   y2=y1+(deltay/-escalar);
               }
                    xfinal.setText(Integer.toString(x2));
                    yfinal.setText(Integer.toString(y2));
        }

        obj.DDA(t, x1, y1, x2, y2);
        
       
    }//GEN-LAST:event_EscalarLineaActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        
        
        if (jComboBox1.getSelectedItem()== "Dibujar"){
            xinicial.setEnabled(true);
            yinicial.setEnabled(true);
            xfinal.setEnabled(true);
            yfinal.setEnabled(true);
            esc.setEnabled(false);
            trasx.setEnabled(false);
            trasy.setEnabled(false);
            rotar.setEnabled(false);
        }
        else if (jComboBox1.getSelectedItem() == "Transformar")
        {
            xinicial.setEnabled(false);
            yinicial.setEnabled(false);
            xfinal.setEnabled(false);
            yfinal.setEnabled(false);
            esc.setEnabled(true);
            trasx.setEnabled(true);
            trasy.setEnabled(true);
            rotar.setEnabled(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void rotarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rotarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rotarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrarLinea;
    private javax.swing.JButton DibujarLinea;
    private javax.swing.JButton EscalarLinea;
    private javax.swing.JPanel PanelDibujoLinea;
    private javax.swing.JButton TrasladarLinea;
    private javax.swing.JTextField esc;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField rotar;
    private javax.swing.JTextField trasx;
    private javax.swing.JTextField trasy;
    private javax.swing.JTextField xfinal;
    private javax.swing.JTextField xinicial;
    private javax.swing.JTextField yfinal;
    private javax.swing.JTextField yinicial;
    // End of variables declaration//GEN-END:variables
}
