/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_comp_grafica.MisPaneles;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;

/**
 *
 * @author jorgeandrade
 */
public class PanelLinea extends javax.swing.JPanel {

    @Override
    public void paint(Graphics g) {
        super.paint(g); 
        
        
    }

    
    public PanelLinea() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        xinicial = new javax.swing.JTextField();
        xfinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yfinal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        yinicial = new javax.swing.JTextField();
        PanelDibujoLinea = new javax.swing.JPanel();
        DibujarLinea = new javax.swing.JButton();
        BotonBorrarLinea = new javax.swing.JButton();
        TrasladarLinea = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        trasy = new javax.swing.JTextField();
        trasx = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        EscalarLinea = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        esc = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setText("Escriba los siguientes datos para dibujar la linea:");

        jLabel2.setText("Punto 1:");

        jLabel3.setText("Punto 2:");

        jLabel4.setText("X");

        jLabel5.setText("X");

        yfinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yfinalActionPerformed(evt);
            }
        });

        jLabel6.setText("Y");

        jLabel7.setText("Y");

        PanelDibujoLinea.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelDibujoLineaLayout = new javax.swing.GroupLayout(PanelDibujoLinea);
        PanelDibujoLinea.setLayout(PanelDibujoLineaLayout);
        PanelDibujoLineaLayout.setHorizontalGroup(
            PanelDibujoLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelDibujoLineaLayout.setVerticalGroup(
            PanelDibujoLineaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        DibujarLinea.setBackground(new java.awt.Color(153, 204, 255));
        DibujarLinea.setText("Dibujar");
        DibujarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DibujarLineaActionPerformed(evt);
            }
        });

        BotonBorrarLinea.setBackground(new java.awt.Color(255, 102, 102));
        BotonBorrarLinea.setText("Borrar");
        BotonBorrarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBorrarLineaActionPerformed(evt);
            }
        });

        TrasladarLinea.setText("Trasladar");
        TrasladarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrasladarLineaActionPerformed(evt);
            }
        });

        jLabel8.setText("Trasladar:");

        jLabel9.setText("X");

        jLabel10.setText("Y");

        EscalarLinea.setText("Escalar");
        EscalarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EscalarLineaActionPerformed(evt);
            }
        });

        jLabel11.setText("Escalar:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(96, 270, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(322, 322, 322))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(263, 263, 263))
                            .addComponent(PanelDibujoLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(xinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(trasx, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(trasy, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(59, 59, 59)
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(xfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TrasladarLinea)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel11)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(esc, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(DibujarLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BotonBorrarLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(EscalarLinea))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(xfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(yfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)
                            .addComponent(DibujarLinea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BotonBorrarLinea))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel12)
                                .addGap(22, 22, 22))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(trasx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9)
                                        .addComponent(jLabel8))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(trasy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel10)
                                        .addComponent(TrasladarLinea)
                                        .addComponent(jLabel11)
                                        .addComponent(esc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(EscalarLinea)))
                                .addGap(18, 33, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(xinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(PanelDibujoLinea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DibujarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DibujarLineaActionPerformed
        Graphics t = PanelDibujoLinea.getGraphics();
        
        //Obtener colores random
        Random rand = new Random();
        float r = rand.nextFloat();
        float g = rand.nextFloat();
        float b = rand.nextFloat();
        Color randomColor = new Color(r, g, b);

        //obtener valores por teclado del usuario
        int x1,x2,y1,y2;
        x1=Integer.parseInt(xinicial.getText());
        y1=Integer.parseInt(yinicial.getText());
        x2=Integer.parseInt(xfinal.getText());
        y2=Integer.parseInt(yfinal.getText());
        
        //Variables para el metodo DDA
        float xi,yi,xf,yf;
        float deltax,deltay,k;
        float xinc,yinc;
       // int xinc2;
        //int yinc2;

        
        
        
        
        //comienza el metodo DDA-----------------------------------------
        
       
        deltax=x2-x1;
        deltay=y2-y1;
        
        if (Math.abs(deltax) > Math.abs(deltay)){
        k=Math.abs(deltax);
        }
        else if (Math.abs(deltay) > Math.abs(deltax)){
            k=Math.abs(deltay);
        }
        else
        {
            k=Math.abs(deltax);
        }
        
        xinc=deltax/k;
        yinc=deltay/k;
       
       
     if(deltax>= 0 && deltay>= 0 )
     {
        if (deltax != 0 && deltay !=0){
            System.out.print("parte 1");
                yi=y1;
            for(xi=x1;xi<=x2;xi=xi+xinc){

                xf=xi+xinc;
                yf=yi+yinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
        }
        else if ( deltax == 0){
            System.out.print("parte 2");
            xi=x1;
            for(yi=y1;yi<=y2;yi=yi+yinc){

                yf=yi+yinc;
                xf=xi+xinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                xi=xi+xinc;
            } 
        }
        else if ( deltay == 0){
            System.out.print("parte 3");
            yi=y1;
            for(xi=x1;xi<=x2;xi=xi+xinc){

                xf=xi+xinc;
                yf=yi+yinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
        }
     }
     else{
        if (deltax != 0 && deltay !=0 && deltay>deltax){
            System.out.print("parte 4");
                yi=y1;
            for(xi=x1;xi>=x2;xi=xi+xinc){

                xf=xi+xinc;
                yf=yi+yinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
        }
        else if (deltax != 0 && deltay !=0 && Math.abs(deltay)>Math.abs(deltax)){
            System.out.print("parte 9");
                xi=x1;
            for(yi=y1;yi>=y2;yi=yi+yinc){

                yf=yi+yinc;
                xf=xi+xinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                xi=xi+xinc;
            } 
        }
        else if (deltax != 0 && deltay !=0 && deltax>deltay){
            System.out.print("parte 5");
                yi=y1;
            for(xi=x1;xi<=x2;xi=xi+xinc){

                xf=xi+xinc;
                yf=yi+yinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
        }
        else if ( deltax == 0){
            System.out.print("parte 6");
            xi=x1;
            for(yi=y1;yi>=y2;yi=yi+yinc){  //yinc es negativo aqui

                yf=yi-yinc;
                xf=xi-xinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                xi=xi-xinc;
            } 
        }
        else if ( deltay == 0){
            System.out.print("parte 7");
            yi=y1;
            for(xi=x1;xi>=x2;xi=xi+xinc){ //xinc es negativo aqui

                xf=xi-xinc;
                yf=yi-yinc;

                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi-yinc;
            } 
        }
        else if(deltax == deltay ){
            System.out.print("parte 8");
            yi=y1;
            for(xi=x1;xi>=x2;xi=xi+xinc){ //xinc es negativo aqui

                xf=xi+xinc;
                yf=yi+yinc;

                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
            }
           
            
        }
     
     
     //Termina el metodo DDA-----------------------------------------
    }//GEN-LAST:event_DibujarLineaActionPerformed

    private void yfinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yfinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yfinalActionPerformed

    private void BotonBorrarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBorrarLineaActionPerformed
        xinicial.setText(null);
        xfinal.setText(null);
        yinicial.setText(null);
        yfinal.setText(null);
        PanelDibujoLinea.removeAll();
        PanelDibujoLinea.repaint();
    }//GEN-LAST:event_BotonBorrarLineaActionPerformed

    private void TrasladarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrasladarLineaActionPerformed
        
        Graphics t = PanelDibujoLinea.getGraphics();
       
        
        PanelDibujoLinea.removeAll();
        PanelDibujoLinea.repaint();
        
        int tx,ty;
        
        tx=Integer.parseInt(trasx.getText());
        ty=Integer.parseInt(trasy.getText());
        
        int x1,x2,y1,y2;
        x1=Integer.parseInt(xinicial.getText());
        y1=Integer.parseInt(yinicial.getText());
        x2=Integer.parseInt(xfinal.getText());
        y2=Integer.parseInt(yfinal.getText());
        
        x1=x1+tx;
        y1=y1+ty;
        x2=x2+tx;
        y2=y2+ty;
        
        
        
        
        //Obtener colores random
        Random rand = new Random();
        float r = rand.nextFloat();
        float g = rand.nextFloat();
        float b = rand.nextFloat();
        Color randomColor = new Color(r, g, b);
        
        //Variables para el metodo DDA
        float xi,yi,xf,yf;
        float deltax,deltay,k;
        float xinc,yinc;
       // int xinc2;
        //int yinc2;

        
        
        
        
        //comienza el metodo DDA-----------------------------------------
        
       
        deltax=x2-x1;
        deltay=y2-y1;
        
        if (Math.abs(deltax) > Math.abs(deltay)){
        k=Math.abs(deltax);
        }
        else if (Math.abs(deltay) > Math.abs(deltax)){
            k=Math.abs(deltay);
        }
        else
        {
            k=Math.abs(deltax);
        }
        
        xinc=deltax/k;
        yinc=deltay/k;
       
       
     if(deltax>= 0 && deltay>= 0 )
     {
        if (deltax != 0 && deltay !=0){
            System.out.print("parte 1");
                yi=y1;
            for(xi=x1;xi<=x2;xi=xi+xinc){

                xf=xi+xinc;
                yf=yi+yinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
        }
        else if ( deltax == 0){
            System.out.print("parte 2");
            xi=x1;
            for(yi=y1;yi<=y2;yi=yi+yinc){

                yf=yi+yinc;
                xf=xi+xinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                xi=xi+xinc;
            } 
        }
        else if ( deltay == 0){
            System.out.print("parte 3");
            yi=y1;
            for(xi=x1;xi<=x2;xi=xi+xinc){

                xf=xi+xinc;
                yf=yi+yinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
        }
     }
     else{
        if (deltax != 0 && deltay !=0 && deltay>deltax){
            System.out.print("parte 4");
                yi=y1;
            for(xi=x1;xi>=x2;xi=xi+xinc){

                xf=xi+xinc;
                yf=yi+yinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
        }
        else if (deltax != 0 && deltay !=0 && Math.abs(deltay)>Math.abs(deltax)){
            System.out.print("parte 9");
                xi=x1;
            for(yi=y1;yi>=y2;yi=yi+yinc){

                yf=yi+yinc;
                xf=xi+xinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                xi=xi+xinc;
            } 
        }
        else if (deltax != 0 && deltay !=0 && deltax>deltay){
            System.out.print("parte 5");
                yi=y1;
            for(xi=x1;xi<=x2;xi=xi+xinc){

                xf=xi+xinc;
                yf=yi+yinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
        }
        else if ( deltax == 0){
            System.out.print("parte 6");
            xi=x1;
            for(yi=y1;yi>=y2;yi=yi+yinc){  //yinc es negativo aqui

                yf=yi-yinc;
                xf=xi-xinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                xi=xi-xinc;
            } 
        }
        else if ( deltay == 0){
            System.out.print("parte 7");
            yi=y1;
            for(xi=x1;xi>=x2;xi=xi+xinc){ //xinc es negativo aqui

                xf=xi-xinc;
                yf=yi-yinc;

                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi-yinc;
            } 
        }
        else if(deltax == deltay ){
            System.out.print("parte 8");
            yi=y1;
            for(xi=x1;xi>=x2;xi=xi+xinc){ //xinc es negativo aqui

                xf=xi+xinc;
                yf=yi+yinc;

                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
            }
           
            
        }
     
     
     //Termina el metodo DDA-----------------------------------------
    }//GEN-LAST:event_TrasladarLineaActionPerformed

    private void EscalarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EscalarLineaActionPerformed
        Graphics t = PanelDibujoLinea.getGraphics();
        
        //Obtener colores random
        Random rand = new Random();
        float r = rand.nextFloat();
        float g = rand.nextFloat();
        float b = rand.nextFloat();
        Color randomColor = new Color(r, g, b);

        //obtener valores por teclado del usuario
        int x1,x2,y1,y2,escalar;
        x1=Integer.parseInt(xinicial.getText());
        y1=Integer.parseInt(yinicial.getText());
        x2=Integer.parseInt(xfinal.getText());
        y2=Integer.parseInt(yfinal.getText());
        
        escalar=Integer.parseInt(esc.getText());
        
        //Variables para el metodo DDA
        float xi,yi,xf,yf;
        float deltax,deltay,k;
        float xinc,yinc;
       // int xinc2;
        //int yinc2;

        x2=escalar*x2;
        y2=escalar*y2;
        
        
        
        //comienza el metodo DDA-----------------------------------------
        
       
        deltax=x2-x1;
        deltay=y2-y1;
        
        if (Math.abs(deltax) > Math.abs(deltay)){
        k=Math.abs(deltax);
        }
        else if (Math.abs(deltay) > Math.abs(deltax)){
            k=Math.abs(deltay);
        }
        else
        {
            k=Math.abs(deltax);
        }
        
        xinc=deltax/k;
        yinc=deltay/k;
       
       
     if(deltax>= 0 && deltay>= 0 )
     {
        if (deltax != 0 && deltay !=0){
            System.out.print("parte 1");
                yi=y1;
            for(xi=x1;xi<=x2;xi=xi+xinc){

                xf=xi+xinc;
                yf=yi+yinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
        }
        else if ( deltax == 0){
            System.out.print("parte 2");
            xi=x1;
            for(yi=y1;yi<=y2;yi=yi+yinc){

                yf=yi+yinc;
                xf=xi+xinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                xi=xi+xinc;
            } 
        }
        else if ( deltay == 0){
            System.out.print("parte 3");
            yi=y1;
            for(xi=x1;xi<=x2;xi=xi+xinc){

                xf=xi+xinc;
                yf=yi+yinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
        }
     }
     else{
        if (deltax != 0 && deltay !=0 && deltay>deltax){
            System.out.print("parte 4");
                yi=y1;
            for(xi=x1;xi>=x2;xi=xi+xinc){

                xf=xi+xinc;
                yf=yi+yinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
        }
        else if (deltax != 0 && deltay !=0 && Math.abs(deltay)>Math.abs(deltax)){
            System.out.print("parte 9");
                xi=x1;
            for(yi=y1;yi>=y2;yi=yi+yinc){

                yf=yi+yinc;
                xf=xi+xinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                xi=xi+xinc;
            } 
        }
        else if (deltax != 0 && deltay !=0 && deltax>deltay){
            System.out.print("parte 5");
                yi=y1;
            for(xi=x1;xi<=x2;xi=xi+xinc){

                xf=xi+xinc;
                yf=yi+yinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
        }
        else if ( deltax == 0){
            System.out.print("parte 6");
            xi=x1;
            for(yi=y1;yi>=y2;yi=yi+yinc){  //yinc es negativo aqui

                yf=yi-yinc;
                xf=xi-xinc;


                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                xi=xi-xinc;
            } 
        }
        else if ( deltay == 0){
            System.out.print("parte 7");
            yi=y1;
            for(xi=x1;xi>=x2;xi=xi+xinc){ //xinc es negativo aqui

                xf=xi-xinc;
                yf=yi-yinc;

                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi-yinc;
            } 
        }
        else if(deltax == deltay ){
            System.out.print("parte 8");
            yi=y1;
            for(xi=x1;xi>=x2;xi=xi+xinc){ //xinc es negativo aqui

                xf=xi+xinc;
                yf=yi+yinc;

                t.drawLine(Math.round(xi), Math.round(yi), Math.round(xf), Math.round(yf));
                t.setColor(randomColor.brighter());
                yi=yi+yinc;
            } 
            }
           
            
        }
     
     
     //Termina el metodo DDA-----------------------------------------
    }//GEN-LAST:event_EscalarLineaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonBorrarLinea;
    private javax.swing.JButton DibujarLinea;
    private javax.swing.JButton EscalarLinea;
    private javax.swing.JPanel PanelDibujoLinea;
    private javax.swing.JButton TrasladarLinea;
    private javax.swing.JTextField esc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField trasx;
    private javax.swing.JTextField trasy;
    private javax.swing.JTextField xfinal;
    private javax.swing.JTextField xinicial;
    private javax.swing.JTextField yfinal;
    private javax.swing.JTextField yinicial;
    // End of variables declaration//GEN-END:variables
}
