/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_comp_grafica.MisPaneles;

import java.awt.Graphics;

/**
 *
 * @author jorgeandrade
 */
public class PanelTriangulo extends javax.swing.JPanel {

    /**
     * Creates new form PanelTriangulo
     */
    public PanelTriangulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        xinicial = new javax.swing.JTextField();
        xfinal = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        yfinal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        yinicial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PanelDibujoTriangulo = new javax.swing.JPanel();
        DibujarTriangulo = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 255));

        jLabel2.setText("Punto 1:");

        jLabel3.setText("Punto 2:");

        jLabel4.setText("X");

        jLabel5.setText("X");

        jLabel6.setText("Y");

        jLabel7.setText("Y");

        jLabel8.setText("Escriba los siguientes datos para dibujar el triangulo:");

        PanelDibujoTriangulo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelDibujoTrianguloLayout = new javax.swing.GroupLayout(PanelDibujoTriangulo);
        PanelDibujoTriangulo.setLayout(PanelDibujoTrianguloLayout);
        PanelDibujoTrianguloLayout.setHorizontalGroup(
            PanelDibujoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );
        PanelDibujoTrianguloLayout.setVerticalGroup(
            PanelDibujoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 468, Short.MAX_VALUE)
        );

        DibujarTriangulo.setText("Dibujar");
        DibujarTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DibujarTrianguloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(yinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(xfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(DibujarTriangulo))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(PanelDibujoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(xinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(yinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(xfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(yfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(DibujarTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PanelDibujoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DibujarTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DibujarTrianguloActionPerformed
        
        Graphics t = PanelDibujoTriangulo.getGraphics();
        
        int xi,xf,yi,yf;
        xi=Integer.parseInt(xinicial.getText());
        yi=Integer.parseInt(yinicial.getText());
        xf=Integer.parseInt(xfinal.getText());
        yf=Integer.parseInt(yfinal.getText());
        
        float deltax,deltay,punto,x1,y1,x2=0,y2=0;
        
        
        //Inicia metodo de bresenham---------------------------------------------------------------- (punto 1)
        deltax=(float)(xf-xi);
        deltay=(float)(yf-yi);
        System.out.print("deltay: "+deltay+"\n");
        punto= (2*deltay)-deltax;
        
        
        System.out.print("punto: "+punto+"\n");
        y1=yi;
        
      if(deltay>=0){
            
       System.out.print("parte 1: \n");
        for(x1=xi;x1<=xf;x1++){
            
            
            if(punto>=0){
                punto=punto+(2*deltay)-(2*deltax);
                x2=x1+1;
                y2=y1+1;
            }
            else{
                punto=punto+(2*deltay);
                x2=x1+1;
                y2=y1;
            }
            
            t.drawLine(Math.round(x1), Math.round(y1), Math.round(x2), Math.round(y2));
            
            y1=y2;
            
            
        }
      }
      else if (deltay <0){
          deltay=Math.abs((float)(yf-yi));
          punto= (2*deltay)-deltax;
          System.out.print("parte 2: \n");
          for(x1=xi;x1<=xf;x1++){
            
            
            if(punto>=0){
                punto=punto+(2*deltay)-(2*deltax);
                x2=x1+1;
                y2=y1-1;
            }
            else{
                punto=punto+(2*deltay);
                x2=x1+1;
                y2=y1;
            }
            
            t.drawLine(Math.round(x1), Math.round(y1), Math.round(x2), Math.round(y2));
            
            y1=y2;
            
            
        }
      }
        
      //Termina metodo de bressenham-----------------------------------------------------------------------(punto 1)
      
      
    }//GEN-LAST:event_DibujarTrianguloActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DibujarTriangulo;
    private javax.swing.JPanel PanelDibujoTriangulo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField xfinal;
    private javax.swing.JTextField xinicial;
    private javax.swing.JTextField yfinal;
    private javax.swing.JTextField yinicial;
    // End of variables declaration//GEN-END:variables
}
