/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto1_comp_grafica.MisPaneles;

import java.awt.Color;
import java.awt.Graphics;
import java.util.Random;
import proyecto1_comp_grafica.Metodos;

/**
 *
 * @author jorgeandrade
 */
public class PanelTriangulo extends javax.swing.JPanel {

    /**
     * Creates new form PanelTriangulo
     */
    public PanelTriangulo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        xinicial = new javax.swing.JTextField();
        xmedio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        ymedio = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        yinicial = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        PanelDibujoTriangulo = new javax.swing.JPanel();
        DibujarTriangulo = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        xfinal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        yfinal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        TrasladarTriangulo = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        trasx = new javax.swing.JTextField();
        trasy = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        BorrarLinea = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setText("Punto 1:");

        jLabel3.setText("Punto 2:");

        xmedio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xmedioActionPerformed(evt);
            }
        });

        jLabel4.setText("X");

        jLabel5.setText("X");

        jLabel6.setText("Y");

        jLabel7.setText("Y");

        jLabel8.setText("Elija una opcion (Dibujar/Transformar):");

        PanelDibujoTriangulo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout PanelDibujoTrianguloLayout = new javax.swing.GroupLayout(PanelDibujoTriangulo);
        PanelDibujoTriangulo.setLayout(PanelDibujoTrianguloLayout);
        PanelDibujoTrianguloLayout.setHorizontalGroup(
            PanelDibujoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelDibujoTrianguloLayout.setVerticalGroup(
            PanelDibujoTrianguloLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
        );

        DibujarTriangulo.setBackground(new java.awt.Color(153, 204, 255));
        DibujarTriangulo.setText("Dibujar");
        DibujarTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DibujarTrianguloActionPerformed(evt);
            }
        });

        jLabel9.setText("Punto 3:");

        jLabel10.setText("X");

        jLabel11.setText("Y");

        TrasladarTriangulo.setText("Tasladar");
        TrasladarTriangulo.setEnabled(false);
        TrasladarTriangulo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TrasladarTrianguloActionPerformed(evt);
            }
        });

        jLabel12.setText("Trasladar");

        trasx.setEnabled(false);
        trasx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trasxActionPerformed(evt);
            }
        });

        trasy.setEnabled(false);

        jLabel13.setText("x:");

        jLabel14.setText("Y:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Dibujar", "Transformar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        BorrarLinea.setBackground(new java.awt.Color(255, 102, 102));
        BorrarLinea.setText("Borrar");
        BorrarLinea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BorrarLineaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel5)
                                        .addGap(56, 56, 56)
                                        .addComponent(jLabel7))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(xfinal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel11)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(ymedio, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(yfinal))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(xmedio, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(xinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(yinicial, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(DibujarTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BorrarLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(84, 84, 84)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(trasx, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(trasy, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(TrasladarTriangulo)))
                .addGap(17, 192, Short.MAX_VALUE))
            .addComponent(PanelDibujoTriangulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(DibujarTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2)
                                .addComponent(xinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(yinicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(4, 4, 4)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(jLabel5)
                                .addComponent(xmedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7)
                                .addComponent(ymedio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel10)
                                .addComponent(xfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel11)
                                .addComponent(yfinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(BorrarLinea, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(trasx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(trasy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TrasladarTriangulo)
                        .addComponent(jLabel14)
                        .addComponent(jLabel12)))
                .addGap(10, 10, 10)
                .addComponent(PanelDibujoTriangulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void DibujarTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DibujarTrianguloActionPerformed
        
        Graphics t = PanelDibujoTriangulo.getGraphics();

        //obtener valores por teclado del usuario
        int x1,x2,x3,y1,y2,y3,x4,y4,incremento=1;
        x1=Integer.parseInt(xinicial.getText());
        y1=Integer.parseInt(yinicial.getText());
        x2=Integer.parseInt(xmedio.getText());
        y2=Integer.parseInt(ymedio.getText());
        x3=Integer.parseInt(xfinal.getText());
        y3=Integer.parseInt(yfinal.getText());
        x4=x1; // para la tercera linea
        y4=y1; // para la tercera linea
        
        
        Metodos obj =new Metodos();
 
    while (incremento != 4){
        
      obj.DDA(t, x1, y1, x2, y2);
        
     incremento++;
     
     if (incremento == 2){
         x1=x2;
         y1=y2;
         x2=x3;
         y2=y3;
     }
     else if (incremento == 3){
         x1=x3;
         y1=y3;
         x2=x4;
         y2=y4;
     }
     
    }  
      
      
    }//GEN-LAST:event_DibujarTrianguloActionPerformed

    private void xmedioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xmedioActionPerformed
      
    }//GEN-LAST:event_xmedioActionPerformed

    private void trasxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trasxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_trasxActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
         if (jComboBox1.getSelectedItem()== "Dibujar"){
            xinicial.setEnabled(true);
            yinicial.setEnabled(true);
            xmedio.setEnabled(true);
            ymedio.setEnabled(true);
            xfinal.setEnabled(true);
            yfinal.setEnabled(true);
            DibujarTriangulo.setEnabled(true);
            TrasladarTriangulo.setEnabled(false);
            trasx.setEnabled(false);
            trasy.setEnabled(false);
            
        }
        else if (jComboBox1.getSelectedItem() == "Transformar")
        {
            xinicial.setEnabled(false);
            yinicial.setEnabled(false);
             xmedio.setEnabled(false);
            ymedio.setEnabled(false);
            xfinal.setEnabled(false);
            yfinal.setEnabled(false);
            DibujarTriangulo.setEnabled(false);
            TrasladarTriangulo.setEnabled(true);
            trasx.setEnabled(true);
            trasy.setEnabled(true);
            
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void TrasladarTrianguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TrasladarTrianguloActionPerformed
         Graphics t = PanelDibujoTriangulo.getGraphics();

        //obtener valores por teclado del usuario
        int x1,x2,x3,y1,y2,y3,x4,y4,incremento=1;
        x1=Integer.parseInt(xinicial.getText());
        y1=Integer.parseInt(yinicial.getText());
        x2=Integer.parseInt(xmedio.getText());
        y2=Integer.parseInt(ymedio.getText());
        x3=Integer.parseInt(xfinal.getText());
        y3=Integer.parseInt(yfinal.getText());
        x4=x1; // para la tercera linea
        y4=y1; // para la tercera linea
        
        int tx,ty;
        
        tx=Integer.parseInt(trasx.getText());
        ty=Integer.parseInt(trasy.getText());
        
        
        x1=x1+tx;
        y1=y1+ty;
        x2=x2+tx;
        y2=y2+ty;
        x3=x3+tx;
        y3=y3+ty;
        x4=x4+tx;
        y4=y4+ty;
        
        xinicial.setText(Integer.toString(x1));
        yinicial.setText(Integer.toString(y1));
        xmedio.setText(Integer.toString(x2));
        ymedio.setText(Integer.toString(y2));
        xfinal.setText(Integer.toString(x3));
        yfinal.setText(Integer.toString(y3));
        
        Metodos obj =new Metodos();
 
    while (incremento != 4){
        
      obj.DDA(t, x1, y1, x2, y2);
        
     incremento++;
     
     if (incremento == 2){
         x1=x2;
         y1=y2;
         x2=x3;
         y2=y3;
     }
     else if (incremento == 3){
         x1=x3;
         y1=y3;
         x2=x4;
         y2=y4;
     }
     
    }
    
    }//GEN-LAST:event_TrasladarTrianguloActionPerformed

    private void BorrarLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BorrarLineaActionPerformed
        xinicial.setText(null);
        yinicial.setText(null);
        xmedio.setText(null);
        ymedio.setText(null);
        xfinal.setText(null);
        yfinal.setText(null);
        PanelDibujoTriangulo.removeAll();
        PanelDibujoTriangulo.repaint();
    }//GEN-LAST:event_BorrarLineaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BorrarLinea;
    private javax.swing.JButton DibujarTriangulo;
    private javax.swing.JPanel PanelDibujoTriangulo;
    private javax.swing.JButton TrasladarTriangulo;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField trasx;
    private javax.swing.JTextField trasy;
    private javax.swing.JTextField xfinal;
    private javax.swing.JTextField xinicial;
    private javax.swing.JTextField xmedio;
    private javax.swing.JTextField yfinal;
    private javax.swing.JTextField yinicial;
    private javax.swing.JTextField ymedio;
    // End of variables declaration//GEN-END:variables
}
